name: Release

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    name: Publish to GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Bootstrap lerna
        run: |
          yarn
          yarn bootstrap

      - name: Bump versions and publish packages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          npx lerna version --yes --conventional-commits --create-release github --message 'chore(release): publish'
          npx lerna publish from-git --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_LERNA }}
